default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres

development:
  <<: *default
  database: Coursetutors_development

test:
  <<: *default
  database: Coursetutors_test

production:
  <<: *default
  database: Coursetutors_production
  username: Coursetutors
  password: <%= ENV['COURSETUTORS_DATABASE_PASSWORD'] %>
